# -*- coding: utf-8 -*-
"""KNN

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZZTZ8FNoEiOTpP4vwzwxRzqo8C6Ax6EM
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
import pandas as pd


df = pd.read_csv('/content/Mastercard_stock_history.csv')


X = df[['Open', 'High', 'Low', 'Volume']]
y = df['Close']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


k = 4
model = KNeighborsRegressor(n_neighbors = k)


model.fit(X_train, y_train)


y_pred = model.predict(X_test)



mse = mean_squared_error(y_test, y_pred)
print(f'MSE: {mse}')
print(f"R²: {model.score(X_test, y_test)}")




import matplotlib.pyplot as plt


plt.figure(figsize=(10, 6))
plt.plot(y_test.values, label='Valores Reais')
plt.plot(y_pred, label='Previsões kNN')
plt.title('Valores Reais vs Previsões kNN')
plt.xlabel('Índice')
plt.ylabel('Preço de Fechamento')
plt.legend()
plt.show()